<a href="https://colab.research.google.com/github/varalakshmikarrepu/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a','b','c','d','e']
})

In [ ]:
pd.DataFrame({
    "A": [10,20,30,40,50],
    "B": ['a','b','c','d','e'],
    "C": np.random.randint(0,9,5)
})

    A  B  C
0  10  a  2
1  20  b  7
2  30  c  5
3  40  d  7
4  50  e  1

In [ ]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=['A','B','C','D']

)

   A  B  C  D
0  1  6  7  5
1  6  4  6  5
2  8  6  6  0
3  1  8  1  7
4  5  3  3  1
5  3  4  0  5
6  4  2  1  3
7  7  1  2  8
8  3  3  7  6
9  3  3  2  7

In [ ]:
np.random.rand(10,3).round(2)

array([[0.77, 0.79, 0.75],
       [0.97, 0.69, 0.4 ],
       [0.57, 0.87, 0.6 ],
       [0.16, 0.74, 0.06],
       [0.05, 0.34, 0.6 ],
       [0.88, 0.7 , 0.63],
       [0.95, 0.38, 0.6 ],
       [0.28, 0.72, 0.46],
       [0.11, 0.85, 0.04],
       [0.4 , 0.64, 0.77]])

In [ ]:
dfx=pd.DataFrame(np.random.rand(10,4).round(2),columns=["A","B","C","D"])

In [ ]:
dfx.to_excel("varam.xlsx")

In [ ]:
pd.read_excel("varam.xlsx")

   Unnamed: 0     A     B     C     D
0           0  0.94  0.21  0.37  0.84
1           1  0.53  0.14  0.77  0.59
2           2  1.00  0.72  0.87  0.85
3           3  0.87  0.96  0.64  0.62
4           4  0.84  0.93  0.34  0.73
5           5  0.80  0.16  0.73  0.30
6           6  0.28  0.32  0.91  0.14
7           7  0.54  0.17  0.87  0.09
8           8  0.01  0.02  0.63  0.22
9           9  0.05  0.45  0.16  0.18

In [ ]:
pd.read_excel("varam.xlsx",index_col="Unnamed: 0")

      A     B     C     D
0  0.94  0.21  0.37  0.84
1  0.53  0.14  0.77  0.59
2  1.00  0.72  0.87  0.85
3  0.87  0.96  0.64  0.62
4  0.84  0.93  0.34  0.73
5  0.80  0.16  0.73  0.30
6  0.28  0.32  0.91  0.14
7  0.54  0.17  0.87  0.09
8  0.01  0.02  0.63  0.22
9  0.05  0.45  0.16  0.18

In [ ]:
df['MM'] = np.random.randint(1,13,5)

In [ ]:
df.describe(include='all')

                A    B         MM
count    5.000000    5   5.000000
unique        NaN    5        NaN
top           NaN    a        NaN
freq          NaN    1        NaN
mean    30.000000  NaN   6.000000
std     15.811388  NaN   3.872983
min     10.000000  NaN   1.000000
25%     20.000000  NaN   3.000000
50%     30.000000  NaN   7.000000
75%     40.000000  NaN   9.000000
max     50.000000  NaN  10.000000

In [ ]:
df['m']=np.random.choice(['a','b','c','d','e'],5)

In [ ]:
df.drop('m',axis=1,inplace=True)

how to use conditions to create a new column

In [ ]:
df['A'] .apply(lambda x : 'big' if x > 5 else 'small')

0    big
1    big
2    big
3    big
4    big
Name: A, dtype: object

In [ ]:
df['A']=df['A'].apply(lambda x : 'big' if x>5 else 'small')

In [ ]:
df

     A      B  MM Category NewCategory
0  big  small   7    small       small
1  big  small   1    small       small
2  big    big   9      big         big
3  big    big  10      big         big
4  big    big   3      big         big